Feature/recipe list
Luxa23/capstone-project pull request #9
Opened 2022-05-25 09:17 UTC by Luxa23

2022-05-25 09:49 UTC, TheMarv requested changes
You might want to rethink the ListEntry component. Unless you want to add more to might, perhaps you should change it to a ul with li instead. If you plan to add more to the ListEntry later on it's fine.

2022-05-25 09:49 UTC, TheMarv commented on components/RecipeForm.js
> +          ></StyledInput>
```suggestion
          />
```

use a self-closing tag

2022-05-25 09:49 UTC, TheMarv commented on pages/index.js
> +      <RecipeForm></RecipeForm>
```suggestion
      <RecipeForm />
```

use self-closing tags

2022-05-29 07:38 UTC, Luxa23 commented on components/ListEntry.js
> +    </StyledListEntry>
since it is the title, yes

2022-05-29 07:48 UTC, merged